# Generated by Django 5.2 on 2025-11-16 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, null=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(null=True)),
                ('tipo', models.CharField(default='porcentaje', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('max_uso', models.IntegerField(null=True)),
                ('usos_realizados', models.IntegerField(default=0)),
                ('aplicable_a', models.CharField(default='todos', max_length=30)),
                ('fecha_inicio', models.DateTimeField(null=True)),
                ('fecha_fin', models.DateTimeField(null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'descuentos',
                'ordering': ['-creado_en'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=100, unique=True)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('producto', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=50)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='core.producto')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
