# Generated by Django 5.1.6 on 2025-11-25 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_token_recuperacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria_producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='core.categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.ForeignKey(blank=True, db_column='descuento_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='core.descuento'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.marca'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proveedor'),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_original',
            field=models.PositiveIntegerField(blank=True, help_text='Stock inicial/predeterminado para calcular porcentajes', null=True),
        ),
    ]
