# Generated by Django 5.1.6 on 2025-11-25 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_producto_cantidad_producto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descuento',
            options={'managed': True, 'ordering': ['-creado_en']},
        ),
        migrations.AlterModelOptions(
            name='imagenproducto',
            options={'managed': True},
        ),
    ]
